// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nts_protobuf/OrderData.proto

package org.nts.protobuf;

public interface OrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.nts.protobuf.Order)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 OrderId = 1;</code>
   * @return The orderId.
   */
  long getOrderId();

  /**
   * <code>string instrumentId = 2;</code>
   * @return The instrumentId.
   */
  java.lang.String getInstrumentId();
  /**
   * <code>string instrumentId = 2;</code>
   * @return The bytes for instrumentId.
   */
  com.google.protobuf.ByteString
      getInstrumentIdBytes();

  /**
   * <code>double qty = 3;</code>
   * @return The qty.
   */
  double getQty();

  /**
   * <code>double limit_price = 4;</code>
   * @return The limitPrice.
   */
  double getLimitPrice();

  /**
   * <code>double market_price = 5;</code>
   * @return The marketPrice.
   */
  double getMarketPrice();
}
