// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nts_protobuf/OrderData.proto

package org.nts.protobuf;

public final class OrderData {
  private OrderData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_nts_protobuf_Order_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_nts_protobuf_Order_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034nts_protobuf/OrderData.proto\022\020org.nts." +
      "protobuf\"f\n\005Order\022\017\n\007OrderId\030\001 \001(\004\022\024\n\014in" +
      "strumentId\030\002 \001(\t\022\013\n\003qty\030\003 \001(\001\022\023\n\013limit_p" +
      "rice\030\004 \001(\001\022\024\n\014market_price\030\005 \001(\001B%\n\020org." +
      "nts.protobufB\tOrderDataP\001\242\002\003GPBb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_nts_protobuf_Order_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_nts_protobuf_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_nts_protobuf_Order_descriptor,
        new java.lang.String[] { "OrderId", "InstrumentId", "Qty", "LimitPrice", "MarketPrice", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
